name: Build and deploy Laravel app to Azure Web App - gestion-tickets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, dom, fileinfo, openssl, pdo, tokenizer, xml

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Prepare Laravel app
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Upload Laravel app artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: |
            app
            bootstrap
            config
            database
            public
            resources
            routes
            storage
            tests
            artisan
            composer.json
            composer.lock
            .env
            phpunit.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Laravel app artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E2E82340D9DE4F73969557A10BFA26C5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EAE63C338B6149E9BB305D0F5941180C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E786CEEA34844E818E0B78F56C8FC8B9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gestion-tickets'
          slot-name: 'Production'
          package: .
